POST http://localhost:8080/api/partner/post http/1.1
Content-type: application/json

{
"name":"john smith",
"email": "chengalvin333@gmail.com",
"phone": "+61 0412345678",
"message": "Hi there!",
"service":"outlook"
}

###

GET http://localhost:8080/api/partner/get?key=A1s2d3f4.888.5165 http/1.1
